---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    ignore: 
      - dependency-name: "jest"
        versions: "^25.5.4"
    pull-request-branch-name:
      separator: "_"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: daily
